version: '3.8'

services:
  sqlserverdb:
    container_name: sqlserverdb
    environment:
        SA_PASSWORD: "Passw0rd!"
        ACCEPT_EULA: "Y"
    restart: always
    volumes:
    - sqlserver_data:/var/lib/sqlserver/data
    ports:
    - "1435:1433"
     
  
